# Generated by Django 3.2.5 on 2021-07-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, unique=True)),
                ('founder', models.CharField(max_length=50)),
                ('headquator', models.CharField(max_length=99)),
                ('fund_raise', models.CharField(max_length=50)),
                ('working', models.CharField(choices=[('working', 'WORKING'), ('close', 'CLOSE')], default='working', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=99)),
                ('experience', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_employee', to='myapp.company')),
            ],
        ),
    ]
