# Generated by Django 3.2.5 on 2021-07-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='created_by',
            new_name='user',
        ),
    ]
