# Generated by Django 3.2.5 on 2021-07-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_name_company_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='name',
        ),
    ]
